### ISSUE TITLE
Index existing issues for a repo that's newly added to this app

### ISSUE THREAD

**Issue by sivakumar-kailasam** [ember-learn/ember-help-wanted-webhook#12]
A lot of repos that would get added to this app would already have issues properly labeled, so we might have to have an indexing module that can be run manually instead of being a web endpoint.

**Comment by acorncom** [comment]
Yep, I'd been thinking the same thing. Nice! Yes something to run against the Github API seems like what we would need. I'd been thinking repo URL and tag (or tags) to find would be the parameters

**Comment by sivakumar-kailasam** [comment]
Implemented in #15
