### ISSUE TITLE
Setup populate script to populate CouchDB

### ISSUE THREAD

**Issue by acorncom** [ember-learn/ember-help-wanted-webhook#23]
Did initial work using the `nano` library we're using to write in our `populate.js` file.  But when I pointed it to the Cloudant setup that we got running earlier today, I got a `_writer access is required for this request` error back.

Don't have a ton of time to look at this.  From what I'm seeing Cloudant's client (https://github.com/cloudant/nodejs-cloudant) wraps nano, so it should work.  But might be just as easy to use the Cloudant client ...

**Comment by sivakumar-kailasam** [comment]
Can you still merge this? I'll try fixing things without the cloudant wrapper

**Comment by acorncom** [comment]
Fixed by https://github.com/ember-learn/ember-help-wanted-webhook/commit/ac212b9be8438ecf0f763257405029d334dcb9d6
